# Use an official Python runtime as a base image
FROM python:3.11

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn
# Copy the application files
COPY . .

# Ensure the SQLite database folder exists
RUN mkdir -p /app/db

# Collect static files
RUN python manage.py collectstatic --noinput

# Expose the port Django will run on
EXPOSE 8000

# Set Python to be unbuffered (for logging)
ENV PYTHONUNBUFFERED=1
