# Generated by Django 5.1.6 on 2025-04-09 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rater_digital_id', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(default='test123', max_length=100)),
                ('active', models.BooleanField()),
                ('task_access', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_time', models.DateTimeField()),
                ('trait', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('assign_all', models.BooleanField(default=False)),
                ('response', models.TextField()),
                ('words_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta', models.IntegerField(null=True)),
                ('gra', models.IntegerField(null=True)),
                ('voc', models.IntegerField(null=True)),
                ('coco', models.IntegerField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='modelapi.rater')),
                ('writing_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='modelapi.writingtask')),
            ],
        ),
    ]
