# Generated by Django 5.1.6 on 2025-04-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beclass',
            name='class_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='writingtask',
            name='trait',
            field=models.CharField(choices=[('Writing 1', 'Writing 1'), ('Writing 2', 'Writing 2'), ('Weekly Writing', 'Weekly Writing')], max_length=25, null=True),
        ),
    ]
