# Generated by Django 5.1.6 on 2025-04-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingtasks',
            name='words_count',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
