# Generated by Django 5.1.6 on 2025-04-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttask',
            name='comments',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
