# Generated by Django 5.1.6 on 2025-02-16 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='rate1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='rate2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='rate3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='rate4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='writing_title', to='modelapi.writingtasks'),
            preserve_default=False,
        ),
    ]
