# Generated by Django 5.1.6 on 2025-02-16 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0002_reviewassignment_rate1_reviewassignment_rate2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writingtasks',
            old_name='title',
            new_name='testId',
        ),
        migrations.RemoveField(
            model_name='reviewassignment',
            name='title',
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='testId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='writing_test', to='modelapi.writingtasks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writingtasks',
            name='itemId',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
