# Generated by Django 5.1.6 on 2025-04-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0002_writingtasks_words_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingtasks',
            name='words_count',
            field=models.IntegerField(null=True),
        ),
    ]
