# Generated by Django 5.1.6 on 2025-04-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0003_alter_writingtasks_words_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='raters',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
