# Generated by Django 5.1.6 on 2025-05-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0003_rename_class_code_beclass_class_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='student_code',
        ),
        migrations.RenameField(
            model_name='writingtask',
            old_name='student_name',
            new_name='student_code',
        ),
    ]
