# Generated by Django 5.1.6 on 2025-02-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0003_rename_title_writingtasks_testid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewassignment',
            name='testId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='writingtasks',
            name='testId',
            field=models.CharField(max_length=50),
        ),
    ]
