# Generated by Django 5.1.6 on 2025-04-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0004_raters_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raters',
            name='active',
            field=models.BooleanField(),
        ),
    ]
