# Generated by Django 5.1.6 on 2025-05-20 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0005_student_student_can'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='writingtask',
            unique_together={('trait', 'student_code', 'started_time')},
        ),
    ]
