# Generated by Django 5.1.6 on 2025-05-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0006_alter_writingtask_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingtask',
            name='trait',
            field=models.CharField(choices=[('Writing 1', 'Writing 1'), ('Writing 2', 'Writing 2'), ('Writing 3', 'Writing 3'), ('Writing 4', 'Writing 4'), ('Weekly Writing', 'Weekly Writing')], max_length=25, null=True),
        ),
    ]
