# Generated by Django 5.1.6 on 2025-07-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0007_alter_writingtask_trait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(choices=[('Rater', 'Rater'), ('Teacher', 'Teacher'), ('Admin', 'Admin'), ('Admin-Rater', 'Admin-Rater'), ('Test-Rater', 'Test-Rater')], default='Rater', max_length=20),
        ),
    ]
