# Generated by Django 5.1.6 on 2025-09-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0008_alter_customuser_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilAppPelaDataSplitsLog',
            fields=[
                ('split_id', models.UUIDField(primary_key=True, serialize=False)),
                ('train_count', models.IntegerField()),
                ('val_count', models.IntegerField()),
                ('test_count', models.IntegerField()),
                ('split_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'util_app_pela_data_splits_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtilAppPelaWritingseed',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('change_reason', models.TextField()),
                ('severity', models.CharField(max_length=50)),
                ('session_id', models.CharField(max_length=255)),
                ('trait', models.CharField(max_length=100)),
                ('response', models.TextField()),
                ('words_count', models.IntegerField()),
                ('started_time', models.DateTimeField()),
                ('test_id', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('user_login', models.CharField(max_length=150)),
                ('timetaken', models.FloatField(blank=True, db_column='timeTaken', null=True)),
                ('data_split', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'util_app_pela_writingseed',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='writingtask',
            name='data_split',
            field=models.CharField(default='train', max_length=10),
        ),
        migrations.AddField(
            model_name='writingtask',
            name='test_id',
            field=models.IntegerField(default=34, null=True),
        ),
    ]
