# Generated by Django 5.1.6 on 2025-10-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0009_utilapppeladatasplitslog_utilapppelawritingseed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingtask',
            name='test_id',
            field=models.IntegerField(default=54, null=True),
        ),
    ]
