# Generated by Django 5.1.6 on 2025-10-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0010_alter_writingtask_test_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingtask',
            name='task_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
