# Generated by Django 5.1.6 on 2025-10-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0011_writingtask_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingtask',
            name='trait',
            field=models.CharField(choices=[('Writing 1', 'Writing 1'), ('Writing 2', 'Writing 2'), ('Writing 3', 'Writing 3'), ('Writing 4', 'Writing 4'), ('Weekly Writing', 'Weekly Writing'), ('PELA3', 'PELA3')], max_length=25, null=True),
        ),
    ]
