# Generated by Django 5.1.6 on 2025-12-10 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0012_alter_writingtask_trait'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmenttask',
            unique_together={('writing_task', 'rater')},
        ),
    ]
